coverage:
  status:
    project:
      default:
        threshold: 90%
    patch:
      default:
        threshold: 90%
ignore:
  - "lua/commons/_system.lua"
  - "lua/commons/_uri.lua"
  - "lua/commons/async.lua"
  - "lua/commons/color/hsl.lua"
