site_name: commons.nvim
site_url: https://linrongbin16.github.io/commons.nvim
site_description: The commons lua library for Neovim plugin project.
site_author: Lin Rongbin (linrongbin16@outlook.com)
copyright: MIT
repo_url: https://github.com/linrongbin16/commons.nvim
edit_uri: blob/main/docs_source/
edit_uri_template: "blob/main/docs_source/{path}"
docs_dir: docs_source
site_dir: docs
nav:
  - Home: index.md
  - Modules:
      - "commons.buffers": commons_buffers.md
      - "commons.fileios": commons_fileios.md
