site_name: commons.nvim
site_url: https://linrongbin16.github.io/commons.nvim
repo_url: https://github.com/linrongbin16/commons.nvim
edit_uri: blob/main/docs_source/
docs_dir: docs_source
site_dir: docs
nav:
  - Home: index.md
  - Modules: modules.md
