local cwd = vim.fn.getcwd()

describe("commons.log", function()
  local assert_eq = assert.is_equal
  local assert_true = assert.is_true
  local assert_false = assert.is_false

  before_each(function()
    vim.api.nvim_command("cd " .. cwd)
  end)

  local log = require("commons.log")
  describe("[log]", function()
    log.setup({
      name = "root",
      level = vim.log.levels.DEBUG,
      use_console = true,
      use_file = true,
      file_name = "logging.txt",
    })

    it("log", function()
      log.log(vim.log.levels.DEBUG, "debug without parameters")
      log.log("INFO", "info with 1 parameters: %s")
      log.log("WARN", "warn with 2 parameters: %s, %d")
      log.log(vim.log.levels.ERROR, "error with 3 parameters: %s, %d, %f")
      local ok, err = pcall(log.log, "ERROR", "error message with pcall")
      assert_true(ok)
    end)
    it("debug", function()
      log.debug("debug without parameters")
      log.debug("debug with 1 parameters: %s")
      log.debug("debug with 2 parameters: %s, %d")
      log.debug("debug with 3 parameters: %s, %d, %f")
    end)
    it("info", function()
      log.info("info without parameters")
      log.info("info with 1 parameters: %s")
      log.info("info with 2 parameters: %s, %d")
      log.info("info with 3 parameters: %s, %d, %f")
    end)
    it("warn", function()
      log.warn("warn without parameters")
      log.warn("warn with 1 parameters: %s")
      log.warn("warn with 2 parameters: %s, %d")
      log.warn("warn with 3 parameters: %s, %d, %f")
    end)
    it("err", function()
      log.err("err without parameters")
      log.err("err with 1 parameters: %s")
      log.err("err with 2 parameters: %s, %d")
      log.err("err with 3 parameters: %s, %d, %f")
    end)
    it("ensure", function()
      log.ensure(true, "ensure without parameters")
      log.ensure(true, "ensure with 1 parameters: %s")
      log.ensure(true, "ensure with 2 parameters: %s, %d")
      log.ensure(true, "ensure with 3 parameters: %s, %d, %f")
      local ok1, err1 = pcall(log.ensure, false, "ensure without parameters")
      print(vim.inspect(err1) .. "\n")
      assert_false(ok1)
      local ok2, err2 = pcall(log.ensure, false, "ensure with 1 parameters: %s")
      print(vim.inspect(err2) .. "\n")
      assert_false(ok2)
      local ok3, err3 = pcall(log.ensure, false, "ensure with 2 parameters: %s, %d")
      print(vim.inspect(err3) .. "\n")
      assert_false(ok3)
      local ok4, err4 = pcall(log.ensure, false, "ensure with 3 parameters: %s, %d, %f", "a")
      print(vim.inspect(err4) .. "\n")
      assert_false(ok4)
    end)
    it("throw", function()
      local ok1, msg1 = pcall(log.throw, "throw without params")
      assert_false(ok1)
      assert_eq(type(msg1), "string")
      local ok2, msg2 = pcall(log.throw, "throw with 1 params: %s")
      assert_false(ok2)
      assert_eq(type(msg2), "string")
      local ok3, msg3 = pcall(log.throw, "throw with 2 params: %s, %d")
      assert_false(ok3)
      assert_eq(type(msg3), "string")
    end)
  end)
end)
