local cwd = vim.fn.getcwd()

describe("commons.tbl", function()
  local assert_eq = assert.is_equal
  local assert_true = assert.is_true
  local assert_false = assert.is_false

  before_each(function()
    vim.api.nvim_command("cd " .. cwd)
  end)

  local tbl = require("commons.tbl")

  describe("strings", function()
    it("tbl_empty/tbl_not_empty", function()
      assert_true(tbl.tbl_empty(nil))
      assert_true(tbl.tbl_empty({}))
      assert_false(tbl.tbl_not_empty(nil))
      assert_false(tbl.tbl_not_empty({}))
      assert_false(tbl.tbl_empty({ 1, 2, 3 }))
      assert_false(tbl.tbl_empty({ a = 1 }))
      assert_true(tbl.tbl_not_empty({ 1, 2, 3 }))
      assert_true(tbl.tbl_not_empty({ a = 1 }))
    end)
    it("tbl_contains", function()
      assert_true(tbl.tbl_contains({ a = 1, b = 2, c = 3, d = 4 }, 1))
      assert_true(tbl.tbl_contains({ a = 1, b = { 1, 2 }, c = 3, d = 4 }, { 1, 2 }, vim.deep_equal))
      assert_false(tbl.tbl_contains({ a = 1, b = 2, c = 3, d = 4 }, "a"))
      assert_false(tbl.tbl_contains({ a = 1, b = { 1, 2 }, c = 3, d = 4 }, { 1, 2 }))
    end)
    it("list", function()
      assert_true(tbl.list_empty(nil))
      assert_true(tbl.list_empty({}))
      assert_false(tbl.list_empty({ 1, 2, 3 }))
      assert_true(tbl.list_empty({ a = 1 }))
    end)
    it("list_contains", function()
      assert_true(tbl.list_contains({ 1, 2, 3, 4 }, 1))
      assert_true(tbl.list_contains({ 1, { 1, 2 }, 3, 4 }, { 1, 2 }, vim.deep_equal))
      assert_false(tbl.list_contains({ 1, 2, 3, 4 }, "a"))
      assert_false(tbl.list_contains({ 1, { 1, 2 }, 3, 4 }, { 1, 2 }))
    end)
  end)
end)
