name: Docs
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
concurrency:
  group: ${{ github.ref }}-docs
  cancel-in-progress: true
jobs:
  mkdocs:
    name: PR Conventional Commit
    if: ${{ github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo " start at"
          echo $PWD
      - uses: actions/checkout@v4
      - name: Install Python3
        shell: bash
        run: |
          sudo apt-get install -y python3 python3-dev python3-venv python3-pip python3-docutils
          python3 -m pip install --user mkdocs
          python3 -m mkdocs gh-deploy --force -d ./docs
